repos:
 - repo: https://github.com/keep-network/pre-commit-golang.git
   rev: 4cc73f21101f9da1208719b02bbbe0a4c491497e
   hooks:
    - id: go-imports
    - id: go-vet
    - id: go-lint
 - repo: https://github.com/keep-network/pre-commit-hooks.git
   rev: 63e729f
   hooks:
    - id: check-added-large-files
 - repo: local
   hooks:
    - id: lint-sol
      name: 'lint solidity sol'
      entry: /usr/bin/env bash -c "cd solidity-v1 && npm run lint:sol"
      files: '\.sol$'
      language: script
      description: "Checks solidity code according to the package's linter configuration"
    - id: lint-js
      name: 'lint solidity js'
      entry: /usr/bin/env bash -c "cd solidity-v1 && npm run lint:js"
      files: 'solidity-v1\/.*\.js$'
      language: script
      description: "Checks JS code according to the package's linter configuration"
    - id: format-dashboard
      name: 'format dashboard'
      entry: /usr/bin/env bash -c "cd solidity-v1/dashboard && npm run format"
      files: 'solidity-v1/dashboard/'
      language: script
      description: "Checks dashboard code according to the package's formatting configuration"
    - id: lint-faucet-js
      name: 'lint faucet js'
      entry: /usr/bin/env bash -c "cd infrastructure/gcp/keep-test/google-functions/keep-faucet && npm run lint:js"
      files: 'infrastructure\/gcp\/keep-test\/google-functions\/keep-faucet\/.*\.js$'
      language: script
      description: "Checks JS code according to the package's linter configuration"
