repos:
 - repo: https://github.com/keep-network/pre-commit-golang.git
   rev: HEAD
   hooks:
    - id: go-imports
    - id: go-vet
    - id: go-lint
 - repo: https://github.com/keep-network/pre-commit-hooks.git
   rev: HEAD
   hooks:
    - id: check-added-large-files
 - repo: local
   hooks:
    - id: solium
      name: Solidity linter
      language: node
      entry: solium
      files: '\.sol$'
      args:
      - --dir=contracts/solidity/contracts/
      - --config=contracts/solidity/.soliumrc.json
      additional_dependencies:
      - ethlint@1.2.3
