[ethereum]
  URL = "ws://eth-tx-ropsten.test.keep.network:8546"
  URLRPC = "http://eth-tx-ropsten.test.keep.network:8545"

  [ethereum.account]
    Address = "0xaa886f33bfe5cf672effcfdf9c630bdb785802f8"
    KeyFile = "/mnt/keep-client/config/eth-account-keyfile"

  # Contracts are already deployed to the private testnet.  They are subject to change on deployment
  [ethereum.ContractAddresses]
    # Hex-encoded address of KeepRandomBeaconOperator contract
    KeepRandomBeaconOperator = "0x23C62f3AC74Ab575427EEFf37eCddc68fDeD5901"
    # TokenStaking
    TokenStaking = "0x5366837a0a40CD92e5C42c3b8d919046377CC525"
    # Hex-encoded address of KeepRandomBeaconService contract. Only needed
    # in cases where the client's utility functions will be used (e.g., the
    # relay subcommand).
    KeepRandomBeaconService = "0x6eaC1E4eEFFEb463eBbe4f65efcE64D5d5bD8076"

# We can configure multiple bootstrap peers.  For the purpose of initial testing we're keeping it at one.
[LibP2P]
  Peers = ["/dns4/bootstrap-4.test.keep.network/tcp/3919/ipfs/16Uiu2HAmDKyX7xmLMEAuWtDw5oBLN3L9xtKXSFn8hUEVtukZkuHp", "/dns4/bootstrap-3.test.keep.network/tcp/3919/ipfs/16Uiu2HAm359ykqT4QAehewxGLCqY7vTNHLP1ao9EjieZS8jdeKp5", "/dns4/bootstrap-2.test.keep.network/tcp/3919/ipfs/16Uiu2HAmS29jNiEX2vAtcjZVhPjU5HWKZNjpWj1gp4SKMGwnSfrg", "/dns4/bootstrap-1.test.keep.network/tcp/3919/ipfs/16Uiu2HAm8SrKDSKZnj3syGjQ1B8F6bDokP93wikjUgpdx4sWCN5L"]
  Port = 3919
  # AnnouncedAddresses:
  # Leaving AnnouncedAddresses empty will set a default address to be
  # announced to the network.  The default address will vary by deploy
  # conditions.  Set AnnouncedAddresses if you have known external IPs
  # or DNS entries you want to route traffic through.
  AnnouncedAddresses = []

# In the real world this directory should be on persistent storage.
[Storage]
  DataDir = "/mnt/keep-client/persistence"
