[ethereum]
  URL = "ws://eth-tx.test.keep.network:8546"
  URLRPC = "http://eth-tx.test.keep.network:8545"

  [ethereum.account]
    Address = "0x48f4bb2cf7379467c3052cb8c5d9e3892eeda487"
    KeyFile = "/mnt/keep-client/config/eth-account-keyfile"

  # Contracts are already deployed to the private testnet.  They are subject to change on deployment
  [ethereum.ContractAddresses]
    KeepRandomBeaconOperator = "0xB467bf416520343778eAC8d5f2a64AFA1Fe6C7D1"
    TokenStaking = "0xDE22108189B7D7673Ea66781580aB9e59101c73D"
    KeepRandomBeaconService = "0x45d5844331786e686F4000773aF4db53750446F8"

# We can configure multiple bootstrap peers.  For the purpose of initial testing we're keeping it at one.
[LibP2P]
  Peers = ["/dns4/bootstrap.test.keep.network/tcp/3919/ipfs/16Uiu2HAm9RGTm8VGne5PvZGAw9KYNDggHaEQh5wiGSKgibp2G95r"]
  Port = 3919
  # AnnouncedAddresses:
  # Leaving AnnouncedAddresses empty will set a default address to be
  # announced to the network.  The default address will vary by deploy
  # conditions.  Set AnnouncedAddresses if you have known external IPs
  # or DNS entries you want to route traffic through.
  AnnouncedAddresses = []

# In the real world this directory should be on persistent storage.
[Storage]
  DataDir = "/mnt/keep-client/persistence"
