---
apiVersion: v1
kind: Service
metadata:
  name: eth-tx-internal
  labels:
    app: geth
    type: tx
spec:
  ports:
  - port: 8545
    targetPort: 8545
    name: tcp-8545
  - port: 8546
    targetPort: 8546
    name: tcp-8546
  - port: 30303
    targetPort: 30303
    name: tcp-30303
  - port: 30303
    targetPort: 30303
    name: udp-30303
    protocol: UDP
  selector:
    app: geth
    type: tx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eth-tx-node
  namespace: default
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: geth
      type: tx
  template:
    metadata:
      labels:
        app: geth
        type: tx
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: tx
        image: gcr.io/keep-dev-fe24/eth-geth-node:1.9.6
        imagePullPolicy: Always
        ports:
        - containerPort: 8545
        - containerPort: 8546
        - containerPort: 30303
        env:
        - name: INSTANCE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NETWORKID
          value: "1101"
        - name: WS_SERVER
          value: ws://eth-dashboard.default.svc.cluster.local:3000
        - name: WS_SECRET
          value: BANZAI!!!!
        - name: BOOTNODE_URL
          value: http://eth-dashboard.default.svc.cluster.local:3001
        - name: BOOTNODE_NETWORK
          value: network_1
        - name: BOOTNODE_PUBLIC_IP
          value: eth-dashboard.default.svc.cluster.local
        - name: ETH_IPC_PATH
          value: /tmp/geth.ipc
