[ethereum]
  URL = "wss://ropsten.infura.io/ws/v3/59fb36a36fa4474b890c13dd30038be5"
  URLRPC = "https://ropsten.infura.io/v3/59fb36a36fa4474b890c13dd30038be5"

  [ethereum.account]
    Address = "0xeea0a80cb35ed34093e90559f50188d18e41b574"
    KeyFile = "/mnt/keep-client/config/eth_account_keyfile"

  [ethereum.ContractAddresses]
    # Hex-encoded address of KeepRandomBeaconOperator contract
    KeepRandomBeaconOperator = "0x951b4f181c73506e866aE00A15D58360312c6343"
    # TokenStaking
    TokenStaking = "0x08b914DFd9e46323790FF351CDFe92ee746c9EC7"
    # Hex-encoded address of KeepRandomBeaconService contract. Only needed
    # in cases where the client's utility functions will be used (e.g., the
    # relay subcommand).
    KeepRandomBeaconService = "0x637615ae194d110BFA23424073ceC5fE8547C825"

[LibP2P]
  Peers = ["/dns4/bootstrap-4.test.keep.network/tcp/3919/ipfs/16Uiu2HAmDKyX7xmLMEAuWtDw5oBLN3L9xtKXSFn8hUEVtukZkuHp", "/dns4/bootstrap-3.test.keep.network/tcp/3919/ipfs/16Uiu2HAm359ykqT4QAehewxGLCqY7vTNHLP1ao9EjieZS8jdeKp5", "/dns4/bootstrap-2.test.keep.network/tcp/3919/ipfs/16Uiu2HAmS29jNiEX2vAtcjZVhPjU5HWKZNjpWj1gp4SKMGwnSfrg", "/dns4/bootstrap-0.test.keep.network/tcp/3919/ipfs/16Uiu2HAm8B2HEde1pAUJH31rZehN3isd1ZFiHCdsxjFnGZehuDJZ"]
  Port = 3919
  # AnnouncedAddresses:
  # Leaving AnnouncedAddresses empty will set a default address to be
  # announced to the network.  The default address will vary by deploy
  # conditions.  Set AnnouncedAddresses if you have known external IPs
  # or DNS entries you want to route traffic through.
  AnnouncedAddresses = ["/dns4/bootstrap-1.test.keep.network/tcp/3919"]

[Storage]
  DataDir = "/mnt/keep-client/data"