# This workflow initiates beacon genesis on testnet. The workflow should be
# manually dispatched after the `keep-core` contracts get deployed and
# kubernetes pods get rotated.
name: Genesis Submitter / Testnet

on:
  workflow_dispatch:

jobs:
  submit-genesis:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./solidity-v1
    steps:
      - uses: actions/checkout@v3

      - name: Load environment variables
        uses: keep-network/ci/actions/load-env-variables@v1
        with:
          environment: 'ropsten'

      - uses: actions/setup-node@v3
        with:
          node-version: "14.x"
          cache: "npm"
          cache-dependency-path: solidity-v1/package-lock.json

      - run: npm ci

      - name: Install external keep-core contracts
        env:
          KEEP_CORE_VERSION: ropsten
        run: |
          mkdir external && cd "$_"
          npm init -y
          npm install --quiet --save-exact \
            @keep-network/keep-core@$KEEP_CORE_VERSION
          mkdir -p ../build/contracts
          cp -a node_modules/@keep-network/keep-core/artifacts/. ../build/contracts/
      
      - name: Submit genesis
        env:
          CHAIN_API_URL: ${{ secrets.KEEP_TEST_ETH_HOSTNAME_WS }}
          CONTRACT_OWNER_ACCOUNT_PRIVATE_KEY: |
            ${{ secrets.KEEP_TEST_ETH_CONTRACT_OWNER_PRIVATE_KEY }}
        run: npx truffle exec ./scripts/genesis.js --network $TRUFFLE_NETWORK
