name: Relay Request Submitter / Testnet

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  submit-relay-request:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./solidity-v1
    steps:
      - uses: actions/checkout@v2

      - name: Load environment variables
        uses: keep-network/ci/actions/load-env-variables@v1
        with:
          environment: 'ropsten'

      - uses: actions/setup-node@v3
        with:
          node-version: "14.x"
          cache: "npm"
          cache-dependency-path: solidity-v1/package-lock.json

      - run: npm ci

      - name: Install external keep-core contracts
        env:
          KEEP_CORE_VERSION: ropsten
        run: |
          mkdir external && cd "$_"
          npm init -y
          npm install --quiet --save-exact \
            @keep-network/keep-core@$KEEP_CORE_VERSION
          mkdir -p ../build/contracts
          cp -a node_modules/@keep-network/keep-core/artifacts/. ../build/contracts/

      - name: Submit relay entry request
        env:
          CHAIN_API_URL: ${{ secrets.KEEP_TEST_ETH_HOSTNAME_WS }}
          CONTRACT_OWNER_ACCOUNT_PRIVATE_KEY: |
            ${{ secrets.KEEP_TEST_ETH_CONTRACT_OWNER_PRIVATE_KEY }}
          WATCH_RELAY_ENTRY: true
        run: npx truffle exec ./scripts/request-relay-entry.js --network $TRUFFLE_NETWORK
